
# Refer to https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html for env args
version: "3.9" 
services:
  modsim1:
    ports:
      - '8888:8888'
      - '8889:8889'
      - '1111:22'
    dns:
      - 8.8.8.8
    user: root
    environment:
      - NB_USER=jovyan
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=myFiles
    volumes:
      - ./myFiles:/home/jovyan/myFiles
    image: anaegel/modsim1:latest
volumes:
  myFiles:
    external: true
